// Sample book database
const books = [
    {
        id: 1,
        title: "The Midnight Library",
        author: "Matt Haig",
        genre: "fiction",
        price: 15.99,
        format: "hardcover",
        language: "english",
        publicationYear: 2023,
        description: "Between life and death there is a library. When Nora finds herself in the Midnight Library, she has a chance to make things right.",
        rating: 4.5,
        reviews: 2800,
        imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-4.0.3"
    },
    {
        id: 2,
        title: "Atomic Habits",
        author: "James Clear",
        genre: "non-fiction",
        price: 19.99,
        format: "hardcover",
        language: "english",
        publicationYear: 2024,
        description: "Transform your life with tiny changes in behaviour, starting now.",
        rating: 4.8,
        reviews: 3500,
        imageUrl: "https://images.unsplash.com/photo-1589998059171-988d887df646?ixlib=rb-4.0.3"
    },
    {
        id: 3,
        title: "The Way of Kings",
        author: "Brandon Sanderson",
        genre: "fantasy",
        price: 24.99,
        format: "hardcover",
        language: "english",
        publicationYear: 2022,
        description: "Epic fantasy at its most sublime, introducing the world of Roshar and the Stormlight Archive series.",
        rating: 4.9,
        reviews: 4200,
        imageUrl: "https://images.unsplash.com/photo-1518744713037-f790d943a679?ixlib=rb-4.0.3"
    },
    {
        id: 4,
        title: "The Silent Patient",
        author: "Alex Michaelides",
        genre: "mystery",
        price: 12.99,
        format: "paperback",
        language: "english",
        publicationYear: 2023,
        description: "A woman's act of violence against her husband, and the therapist obsessed with uncovering her motive.",
        rating: 4.6,
        reviews: 2100,
        imageUrl: "https://images.unsplash.com/photo-1587876931567-564ce588bfbd?ixlib=rb-4.0.3"
    },
    {
        id: 5,
        title: "Project Hail Mary",
        author: "Andy Weir",
        genre: "sci-fi",
        price: 16.99,
        format: "ebook",
        language: "english",
        publicationYear: 2024,
        description: "A lone astronaut must save humanity from extinction in this thrilling interstellar adventure.",
        rating: 4.7,
        reviews: 3100,
        imageUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?ixlib=rb-4.0.3"
    },
    {
        id: 6,
        title: "Pride and Prejudice",
        author: "Jane Austen",
        genre: "romance",
        price: 9.99,
        format: "paperback",
        language: "english",
        publicationYear: "older",
        description: "A classic tale of love, pride, and social expectations in 19th century England.",
        rating: 4.7,
        reviews: 5200,
        imageUrl: "https://images.unsplash.com/photo-1603162525937-96b0d83f2b82?ixlib=rb-4.0.3"
    },
    {
        id: 7,
        title: "Think Like a Monk",
        author: "Jay Shetty",
        genre: "non-fiction",
        price: 18.99,
        format: "hardcover",
        language: "english",
        publicationYear: 2023,
        description: "Train your mind for peace and purpose every day with ancient wisdom for modern life.",
        rating: 4.6,
        reviews: 2800,
        imageUrl: "https://images.unsplash.com/photo-1602557625338-74c5ef1b8c93?ixlib=rb-4.0.3"
    },
    {
        id: 8,
        title: "Mistborn: The Final Empire",
        author: "Brandon Sanderson",
        genre: "fantasy",
        price: 14.99,
        format: "paperback",
        language: "english",
        publicationYear: "older",
        description: "A thrilling fantasy adventure where a young thief discovers her destiny in a world ruled by an immortal emperor.",
        rating: 4.8,
        reviews: 3900,
        imageUrl: "https://images.unsplash.com/photo-1535666669445-e8c15cd2e7d9?ixlib=rb-4.0.3"
    },
    {
        id: 9,
        title: "The Thursday Murder Club",
        author: "Richard Osman",
        genre: "mystery",
        price: 13.99,
        format: "ebook",
        language: "english",
        publicationYear: 2024,
        description: "Four retirees meet weekly to solve cold cases, but find themselves in the middle of a real murder investigation.",
        rating: 4.5,
        reviews: 2400,
        imageUrl: "https://images.unsplash.com/photo-1585158531004-3224babed121?ixlib=rb-4.0.3"
    },
    {
        id: 10,
        title: "Dune",
        author: "Frank Herbert",
        genre: "sci-fi",
        price: 17.99,
        format: "hardcover",
        language: "english",
        publicationYear: "older",
        description: "A masterpiece of science fiction that tells the story of a noble family's attempt to control a desert planet.",
        rating: 4.8,
        reviews: 4800,
        imageUrl: "https://images.unsplash.com/photo-1546521343-4eb2c9aa8de5?ixlib=rb-4.0.3"
    },
    {
        id: 11,
        title: "El Laberinto de los Espíritus",
        author: "Carlos Ruiz Zafón",
        genre: "mystery",
        price: 21.99,
        format: "hardcover",
        language: "spanish",
        publicationYear: 2022,
        description: "La aventura final de la saga del Cementerio de los Libros Olvidados.",
        rating: 4.7,
        reviews: 1800,
        imageUrl: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?ixlib=rb-4.0.3"
    },
    {
        id: 12,
        title: "L'Étranger",
        author: "Albert Camus",
        genre: "fiction",
        price: 11.99,
        format: "paperback",
        language: "french",
        publicationYear: "older",
        description: "Un roman philosophique explorant l'absurdité de la vie à travers le personnage de Meursault.",
        rating: 4.6,
        reviews: 2200,
        imageUrl: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?ixlib=rb-4.0.3"
    }
];
